### ISSUE TITLE
Some kaomoji don't render properly

### ISSUE THREAD

**Issue by noaccOS** [cspeterson/splatmoji#19]
Lenny looks fine in selection and in emoticons file
![image](https://user-images.githubusercontent.com/24324352/79969918-71f20700-8492-11ea-9060-94c926fdb112.png)

But when I type it it looks weird
![image](https://user-images.githubusercontent.com/24324352/79969618-07d96200-8492-11ea-8950-df43bccd7e5c.png)

I don't think it's a font problem because I noticed the same behavior in both Roboto and JetBrains Mono
The config file is untouched

**Comment by cspeterson** [comment]
1. Share with me the raw text of the non-working Lennies along with some working ones? Could be some unicode stuff being difficult and I'd like a closer look. And if you have put a bunch of Lennyfaces into a tsv, I'd be interested in integrating it into the included emoticon db 🙂
2. Is it behaving against expectations when using `copy` mode, or only with `type`? Because xdotool can just be generally finnicky with many different applications, so it may be one of those situations.
3. I just pushed new code today that changes slightly how the script hands the selection to xdotool so maybe also just try that while you're at it 😁

**Comment by noaccOS** [comment]
1. I just added the tag `lenny` to the already existing `happy, think` lenny face. Shrug works as expected

2. With `copy` it seems to work as expected

3. I tried it but there is no difference ¯\_(ツ)_/¯

**Comment by noaccOS** [comment]
It seems to be xdotool to me

The first one doesn't render properly for some reason but it is correct, the second is just plain wrong
![image](https://user-images.githubusercontent.com/24324352/80195906-dc36b300-861c-11ea-8c1b-97633491c57b.png)

**Comment by cspeterson** [comment]
HMM I was actually looking at this like it was the usual "xdotool misses characters" problem, but I'm realizing now it's that the wrong characters are coming through. Sorry!

Take a look at this issue: https://github.com/jordansissel/xdotool/issues/97

what locale are you operating under(`locale`)? does running `setxkbmap <keybd layout>` like in that issue change anything?

**Comment by noaccOS** [comment]
My locale is just `en_US.UTF-8`
As mentioned in the issue you mentioned, just typing `setxkbmap` without any arguments fixes the rendering of the kaomoji
![image](https://user-images.githubusercontent.com/24324352/81797189-bd865680-950e-11ea-990e-b8a00a38db0a.png)
A somewhat brutal solution might be to run `setxkbmap` before every `xdotool`?

**Comment by cspeterson** [comment]
Closing this because it does appear to be an xdotool problem not a splatmoji problem, and also maybe resolved by new xdotool fwiw

@noaccOS are you on a newer xdotool at this point? do you still need to muck with keymaps?
